/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

--Retrieves total customers by country
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Retrieves total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Retrieves total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--Retrieves average cost by category
SELECT 
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost  DESC

--Total Revenue Generated for each category
SELECT 
p.category,
SUM(f.sales) AS total_revenue
FROM gold.dim_products p 
LEFT JOIN gold.fact_sales f 
ON f.product_key=p.product_key
WHERE p.category is not null--some products don't have categories
GROUP BY p.category
ORDER BY total_revenue DESC

--Total Revenue generated by each customer
SELECT 
c.first_name,
c.last_name,
SUM(f.sales) AS total_revenue
FROM gold.dim_customers c 
LEFT JOIN gold.fact_sales f 
ON f.customer_key=c.customer_key
GROUP BY c.first_name,c.last_name
ORDER BY total_revenue DESC;

--What is the distribution of items sold across countries
SELECT 
c.country,
SUM(f.quantity) AS total_quantity
FROM gold.dim_customers c 
LEFT JOIN gold.fact_sales f 
ON f.customer_key=c.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;
